#pragma once

#define TAP_CODE_DELAY 5

// More layers
#define DYNAMIC_KEYMAP_LAYER_COUNT 8

// #define TAPPING_TERM 200
// #define PERMISSIVE_HOLD
// #define IGNORE_MOD_TAP_INTERRUPT
// #define TAPPING_FORCE_HOLD
// #define RETRO_TAPPING

#define KEYBALL_CPI_DEFAULT 1000
#define PRECISION_MODE_CPI 300
#define PRECISION_MODE_SCROLL_DIV 6
